language: cpp

dist: bionic

compiler:
- gcc

os:
- linux

branches:
    only:
    - master

notifications:
    email: false

before_install:
- sudo apt-get update -qq

install:
- sudo apt-get install libboost-test-dev

script:
- autoreconf -f -i
- ./configure CXXFLAGS=--std=c++11
- make
- cd tests; autoreconf -f -i
- cd tests; ./configure CXXFLAGS=--std=c++11
- cd tests; make
- cd tests; ./coffi_test
- cd tests; make check
